apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: "backend-service"
spec:
  selector:
    app: backend
  type: LoadBalancer
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000