apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: app
          image: jamesangel/alltunes-backend
          ports:
            - containerPort: 8000
        - name: sidecar
          image: jamesangel/sidecar
          ports:
          - containerPort: 8001
