apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: "client-service"
spec:
  selector:
    app: client
  type: LoadBalancer
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000