apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: "client-service"
spec:
  selector:
    app: client
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer
  loadBalancerIP: "35.246.33.106"