apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: room-service
  template:
    metadata:
      labels:
        app: room-service
    spec:
      containers:
        - name: app
          image: jamesangel/alltunes-room-service
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP